### ISSUE TITLE
FormInput width doesn't work well with VStack

### ISSUE THREAD

**Issue by justin22** [surveysparrow/twigs#121]
**Describe the bug**
When `FormInput` is used in `VStack`, `FormInput` doesn't stretch too 100% width.

**To Reproduce**

```
<Box css={{ width: "600px" }}>
   <VStack alignY="left" gap="$4">
        <FormInput label="Email address" />
           {/* width: "100%" is pointless here */}
        <FormInput label="Name" css={{ width: "100%" }} />
        <Box
            css={{ backgroundColor: "red", height: "10px", width: "100%" }}
        />
   </VStack>
</Box>
```

**Expected behavior**
The styles should be applied to `FormInput`, and not `Input`

**Screenshots**
![image](https://github.com/user-attachments/assets/3b61cb13-1d2a-46f1-889f-aa89dba66530)
![image](https://github.com/user-attachments/assets/f954bb04-0313-4fe4-9e66-54cd7ac908cf)

**Comment by akzhysparrow** [comment]
As a workaround, we can apply `align-items: stretch` on `VStack`

```
<VStack alignY="left" gap="$4" css={{
  alignItems: "stretch"
}}>
```

**Comment by justin-ss** [comment]
> As a workaround, we can apply `align-items: stretch` on `VStack`
> 
> ```
> <VStack alignY="left" gap="$4" css={{
>   alignItems: "stretch"
> }}>
> ```

This is enough I think. Original request is addressed with this in a neater way.
