### ISSUE TITLE
Update toaster content based on id

### ISSUE THREAD

**Issue by justin-ss** [surveysparrow/twigs#25]
### Scenario

I’m creating a record from UI. 
- When I submit, the toast will say “Creating, please wait”. 
- And when the API resolves successfully, i can update the same toast content to "Created successfully". 

This will avoid the need to trigger multiple toaster. 

sample API
```js
toast.current.update({
   title: '',
  description: ''
})```

**Comment by shanuflash** [comment]
Support for promises would be nice too, similar to [sonner toast](https://sonner.emilkowal.ski/). something like 
```
const promise = () => new Promise((resolve) => setTimeout(() => resolve({ name: 'toast' }), 2000));

toast.promise(promise, {
  loading: 'Creating...',
  success: (data) => {
    return `${data.name} created successfully!`;
  },
  error: 'Error while creating ${data.name}',
});
```
