### ISSUE TITLE
Dialogs Manager for Open and Alert variant need a control over modal close

### ISSUE THREAD

**Issue by shettyMegh9** [surveysparrow/twigs#89]
**Describe the bug**
When we are using dialogs.open, assume that confirmButtonProps onClick is a async func. Dialogs should not close until API call is done but currently its closing dialog onClick itself.

**To Reproduce**
Steps to reproduce the behaviour:
1. Use dialogs function open variant or alert variant
2. Pass Async function to confirmButtonProps onClick
3. Click confirm btn, it will close immediately

**Expected behaviour**
Dialog should close only after API call is done

**Comment by akzhysparrow** [comment]
#125 Fixes this
